all:
	cp ../common/src/*  ../libpixy_m0/src
	cp ../common/inc/*  ../libpixy_m0/inc
	cp ../common/src/*  ../libpixy_m4/src
	cp ../common/inc/*  ../libpixy_m4/inc
	cp ../../common/src/*  ../libpixy_m4/src
	cp ../../common/inc/*  ../libpixy_m4/inc
